### ISSUE TITLE
Show last release date and allow sorting based on the date

### ISSUE THREAD

**Issue by szabgab** [davorg/dashboard#12]
Maybe even allow the author to configure if they want the default sorting to be abc or date.

Maybe even have start-date, to display only distributions that were released after that date. (or have a clear separation between "old" and "new" releases.

In general I'd primarily only care about my recent distributions as I don't plan to invest energy in old ones, nut until there is a reason to upload a new version of them.

**Comment by davorg** [comment]
Added a release date column and made that and the distribution name sortable. If you still want the cut-off date, then please raise a separate issue for it.
