### ISSUE TITLE
Have a default image if there's not a badge for something

### ISSUE THREAD

**Issue by briandfoy** [davorg/dashboard#13]
For example, not all of my repos have GitHub Actions configured.

I think this may work, but I haven't had time to play with this yet ([Stackoverflow](https://stackoverflow.com/a/49852701/2766176):

```
$('img').error(function() {
    $(this).attr('src', '/no-img.png').addClass('no-img');
});
```

**Comment by davorg** [comment]
I like the look of these HTML or CSS solutions - https://stackoverflow.com/questions/980855/inputting-a-default-image-in-case-the-src-attribute-of-an-html-img-is-not-vali

**Comment by briandfoy** [comment]
I have a PR in #15 just so you can see what I did, but I think there's a lot of commits you won't want in that. Cherry pick or copy, or whatever.

**Comment by davorg** [comment]
Done.
