### ISSUE TITLE
Most recently uploaded distributions

### ISSUE THREAD

**Issue by szabgab** [davorg/dashboard#17]
What do you think about a page e.g. /recent that would show the N most recently uploaded distributions regardless of author?

**Comment by davorg** [comment]
I think it's a great idea in principle. But, in practice:

* Most uploads won't have any CI info to display
* We won't know which CI services the recent uploads use

**Comment by szabgab** [comment]
I am working on the CPAN::Digger web site https://cpan-digger.perlmaven.com/ that will show some of the data of the most recent releases.
