### ISSUE TITLE
Move the Travis-CI setup instructions to a page

### ISSUE THREAD

**Issue by szabgab** [davorg/dashboard#23]
I think instead of having it in the README the instructions about Travis-CI (and GitHub Actions etc.) should be in a web page.
That page can then be linked from the Dashboard or from the menu of the site.

**Comment by davorg** [comment]
Oh, that's definitely true. I've been concentrating on getting working and assuming that authors will know (or can find out from elsewhere) how to configure the services. But I'm planning to improve the instructions over the next couple of days.

**Comment by briandfoy** [comment]
Maybe dump the Travis stuff now that they have gone to the dark side?

**Comment by davorg** [comment]
Definitely

**Comment by szabgab** [comment]
#44 will remove Travis from the README
