### ISSUE TITLE
Bugs column with RT bug?

### ISSUE THREAD

**Issue by szabgab** [davorg/dashboard#33]
Thanks for adding the Bugs column.
Is it now showing a different bug for RT and anything else?
Maybe there could be some indications where the explicit bugtracker information is RT (and a different one where there is no bugtracker)

**Comment by davorg** [comment]
Oh, that's a really good idea. I'll do that later today.

**Comment by davorg** [comment]
Done. See, for example, NHORNE's page - https://cpandashboard.com/NHORNE/

**Comment by szabgab** [comment]
Nice. Thanks.
