### ISSUE TITLE
master vs main

### ISSUE THREAD

**Issue by davorg** [davorg/dashboard#39]
We're starting to see some new GitHub repos appear with a default branch of `main` instead of `master`. This is a problem as we're currently assuming the branch name `master` in some of the image links. So this needs some thinking about.

Three options that immediately spring to mind:

* Accept that it will only work if you're interested in the `main` branch (this might be the quickest fix, but I want to do something cleverer in the medium term)
* Ask authors to list any repos that don't use `master` as the default branch (but I really want to avoid authors having to list their modules if I can possibly avoid it)
* Some kind of GitHub API magic that works out what the default branch is for any given repo

And then there's a wider question of whether authors want to see results for branches other than the default branch.

**Comment by szabgab** [comment]
A while ago @perlpunk suggested me this construct to find out the default branch of a repo

```
% git ls-remote --symref -q | grep ^ref: | grep 'HEAD$'
ref: refs/heads/master  HEAD
```

**Comment by davorg** [comment]
That only works from a checkout, doesn't it? And, currently, when we're building the dashboards, we don't have the git repos checked out - and I'd rather keep it that way if possible.

I've worked out a way to do it with the GitHub API - now I'm just battling rate limits.

**Comment by davorg** [comment]
See https://github.com/davorg/dashboard/commit/45e33ce2b413f04c239c40406129a59e63192a2b

**Comment by perlpunk** [comment]
> That only works from a checkout, doesn't it?

No, it also works with a git url, e.g.
```
% git ls-remote --symref -q git@github.com:yaml/pyyaml | grep ^ref: | grep 'HEAD$'
ref: refs/heads/master	HEAD
```

**Comment by szabgab** [comment]
BTW @perlpunk  why do you need both greps As I can either one of those would work

**Comment by perlpunk** [comment]
@szabgab hm, I don't remember why I did it this way. probably a leftover from experimenting :)
so this should do it:
```
git ls-remote --symref -q [url] | grep '^ref:.*HEAD$'
```

**Comment by davorg** [comment]
Turned out  the best way was to use the GitHub CLI tools with a bit of `jq`.

    gh repo view owner/repo --json defaultBranchRef -q .defaultBranchRef.name

See 44b995e
