### ISSUE TITLE
Codecov.io support

### ISSUE THREAD

**Issue by tobyink** [davorg/dashboard#4]
I started using codecov.io instead of coveralls.io for a repos during a long period the coveralls.io website had issues with sorting/filtering files to see which had worst coverage. (They've fixed the issue now, but it persisted for months!)

It is still pretty valuable to have. Coveralls.io only checks each line is covered; codecov.io tracks branch conditions, so in `foo() ? bar() : baz()`, codecov.io will only be happy if both the `bar` and `baz` functions get called.

Example of codecov:
https://codecov.io/gh/tobyink/p5-type-tiny

**Comment by davorg** [comment]
Can you give me an example of the URL of a codecov.io badge?

**Comment by tobyink** [comment]
https://codecov.io/gh/tobyink/p5-type-tiny/branch/master/graph/badge.svg

**Comment by davorg** [comment]
Ok, I *think* that's working. But I can't be sure as I don't have any repos using Codecov. Do you want to give it a try?

**Comment by tobyink** [comment]
Yep, seems to work.
