### ISSUE TITLE
RT is no longer closing down

### ISSUE THREAD

**Issue by openstrike** [davorg/dashboard#41]
For modules which use RT as their tracker, a mouse-over the "RT" link shows the message 

> This module uses CPAN RT as its bugtracker. This service will be closed down on 2021-03-01.

But of course RT did not close down (thankfully). The second sentence should probably now be removed.

**Comment by davorg** [comment]
Oh! Good point. I'll get on that immediately.

**Comment by davorg** [comment]
Fixed.
