### ISSUE TITLE
Old CI systems still show in dashboard after being removed

### ISSUE THREAD

**Issue by DrHyde** [davorg/dashboard#53]
After I removed Cirrus and Appveyor from my JSON file they still show up in my dashboard

**Comment by davorg** [comment]
I'll be able to look at this (and your other ticket) when I get back to London tomorrow.

**Comment by davorg** [comment]
So it turns out I was an idiot who accidentally turned off the code that actually published the web site (a couple of months ago, it seems!).

Fixed now.

**Comment by DrHyde** [comment]
Thank you!
