### ISSUE TITLE
Support multiple GitHub Action names

### ISSUE THREAD

**Issue by briandfoy** [davorg/dashboard#9]
I have several named workflows that I'd like to track.

**Comment by briandfoy** [comment]
This is here as a wishlist item. I'll look at this when I have a bit more time.

**Comment by briandfoy** [comment]
There's some code in `dashboard.tt` in #15, but I'm not particularly happy with it. It outputs all three links for me even if I don't have that repo configured, so the rows are taller. Also, it vertically "centers" a single GitHub Action badge because the other two are there but handled by the image error handling I used in #13.

Again, take what works and leave the rest.

**Comment by davorg** [comment]
I've pulled in your current implementation. I see the limitations, but it's good enough for now.
